from inventory_monitor.forms.asset import *
from inventory_monitor.forms.asset_type import *
from inventory_monitor.forms.asset_service import *
from inventory_monitor.forms.contract import *
from inventory_monitor.forms.contractor import *
from inventory_monitor.forms.invoice import *
from inventory_monitor.forms.probe import *
from inventory_monitor.forms.rma import *
from inventory_monitor.forms.abra import *
