# Generated by Django 4.0.7 on 2022-09-01 10:14

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('dcim', '0153_created_datetimefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('time', models.DateTimeField()),
                ('device_descriptor', models.CharField(blank=True, max_length=100, null=True)),
                ('site_descriptor', models.CharField(blank=True, max_length=100, null=True)),
                ('location_descriptor', models.CharField(blank=True, max_length=100, null=True)),
                ('part', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('discovered_data', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.location')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name', 'serial', 'time', 'part', 'description', 'device_descriptor', 'device', 'site_descriptor', 'site', 'location_descriptor', 'location', 'category', 'discovered_data'),
            },
        ),
    ]
