# Generated by Django 4.0.7 on 2022-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='discovered_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='probe',
            name='item_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
