# Generated by Django 4.0.7 on 2022-08-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
