# Generated by Django 4.0.7 on 2022-08-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('inventory_monitor', '0002_probe_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probe',
            old_name='device_name',
            new_name='dev_name',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='comment',
        ),
        migrations.AlterField(
            model_name='probe',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device'),
        ),
    ]
