# Generated by Django 4.0.7 on 2022-08-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0002_probe_discovered_data_probe_item_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probe',
            old_name='item_class',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='probe',
            old_name='dev_name',
            new_name='device_descriptor',
        ),
    ]
