# Generated by Django 4.0.7 on 2022-08-23 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('inventory_monitor', '0003_rename_item_class_probe_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probe',
            options={'ordering': ('name', 'serial', 'time', 'part', 'description', 'device_descriptor', 'device', 'site_descriptor', 'site', 'location_descriptor', 'location', 'category', 'discovered_data')},
        ),
        migrations.AddField(
            model_name='probe',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.location'),
        ),
        migrations.AddField(
            model_name='probe',
            name='location_descriptor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='probe',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.site'),
        ),
        migrations.AddField(
            model_name='probe',
            name='site_descriptor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
