# Generated by Django 4.0.7 on 2022-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0003_rename_device_name_probe_dev_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
