# Generated by Django 4.1.3 on 2022-11-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0003_alter_contract_price_invmonfileattachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvMonFileAttachment',
        ),
    ]
