# Generated by Django 4.0.7 on 2022-08-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0004_probe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probe',
            name='created',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='last_updated',
        ),
    ]
