# Generated by Django 4.1.5 on 2023-02-14 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0008_componentservice_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='items',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
