# Generated by Django 4.1.6 on 2023-03-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('inventory_monitor', '0009_alter_component_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('serial', 'serial_actual', 'partnumber', 'device', 'asset_number', 'project', 'site', 'location', 'inventory_item', 'vendor', 'items', 'price', 'order_contract', 'warranty_start', 'warranty_end')},
        ),
        migrations.RenameField(
            model_name='component',
            old_name='inventory',
            new_name='asset_number',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='locality',
            new_name='site',
        ),
        migrations.AddField(
            model_name='component',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='dcim.inventoryitem'),
        ),
        migrations.AddField(
            model_name='component',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='dcim.location'),
        ),
    ]
