# Generated by Django 4.1.6 on 2023-04-04 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_monitor', '0012_probe_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
