# Generated by Django 5.0.6 on 2024-08-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_monitor", "0013_alter_probe_creation_time"),
        ("tenancy", "0015_contactassignment_rename_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contractors",
                to="tenancy.tenant",
            ),
        ),
    ]
