# Generated by Django 5.1.5 on 2025-02-13 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0014_contractor_tenant"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="component",
            table="inventory_monitor_asset",
        ),
    ]
