# Generated by Django 5.1.5 on 2025-02-17 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0200_populate_mac_addresses"),
        ("inventory_monitor", "0016_rename_component_to_asset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="componentservice",
            options={
                "ordering": (
                    "service_start",
                    "service_end",
                    "service_param",
                    "service_price",
                    "service_category",
                    "service_category_vendor",
                    "asset",
                    "contract",
                )
            },
        ),
        migrations.RenameField(
            model_name="componentservice",
            old_name="component",
            new_name="asset",
        ),
        migrations.AlterField(
            model_name="asset",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="dcim.device",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="dcim.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="dcim.location",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="order_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="inventory_monitor.contract",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="dcim.site",
            ),
        ),
    ]
