# Generated by Django 5.1.5 on 2025-02-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0018_rma"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assignment_status",
            field=models.CharField(default="stocked", max_length=30),
        ),
    ]
