# Generated by Django 5.1.5 on 2025-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0019_asset_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="lifecycle_status",
            field=models.CharField(default="new", max_length=30),
        ),
    ]
