# Generated by Django 5.1.5 on 2025-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0122_charfield_null_choices"),
        ("inventory_monitor", "0021_assettype_asset_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assettype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="assettype",
            index=models.Index(fields=["name"], name="inventory_m_name_a65ffe_idx"),
        ),
        migrations.AddIndex(
            model_name="assettype",
            index=models.Index(fields=["slug"], name="inventory_m_slug_e2f652_idx"),
        ),
    ]
