# Generated by Django 5.1.5 on 2025-03-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory_monitor", "0022_alter_assettype_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assigned_object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_object_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("app_label", "dcim"),
                    ("model__in", ("site", "location", "rack", "device", "module")),
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
