# Generated by Django 5.1.5 on 2025-03-03 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0024_copy_to_assigned_object"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": (
                    "serial",
                    "serial_actual",
                    "partnumber",
                    "asset_number",
                    "project",
                    "inventory_item",
                    "vendor",
                    "quantity",
                    "price",
                    "order_contract",
                    "warranty_start",
                    "warranty_end",
                )
            },
        ),
        migrations.RemoveField(
            model_name="asset",
            name="device",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="location",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="site",
        ),
    ]
