# Generated by Django 5.1.5 on 2025-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0025_alter_asset_options_remove_asset_device_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rma",
            old_name="date_shipped",
            new_name="date_replaced",
        ),
        migrations.RemoveField(
            model_name="rma",
            name="tracking_number",
        ),
        migrations.AlterField(
            model_name="rma",
            name="rma_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
