# Generated by Django 5.1.5 on 2025-03-04 09:50

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration removes the serial_actual field after migration 0027 has:
    1. Created RMAs for assets where serial != serial_actual
    2. Updated the serial field to match serial_actual
    """

    dependencies = [
        ("inventory_monitor", "0027_generate_rma_from_serial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": (
                    "serial",
                    "partnumber",
                    "asset_number",
                    "project",
                    "inventory_item",
                    "vendor",
                    "quantity",
                    "price",
                    "order_contract",
                    "warranty_start",
                    "warranty_end",
                )
            },
        ),
        migrations.RemoveField(
            model_name="asset",
            name="serial_actual",
        ),
    ]
