# Generated by Django 5.1.5 on 2025-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dcim", "0200_populate_mac_addresses"),
        ("extras", "0122_charfield_null_choices"),
        ("inventory_monitor", "0028_alter_asset_options_remove_asset_serial_actual"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["serial"], name="invmon_asset_serial_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["partnumber"], name="invmon_asset_partnumber_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["asset_number"], name="invmon_asset_assetnum_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["assignment_status"], name="invmon_asset_assign_status_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["lifecycle_status"], name="invmon_asset_lifecycle_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["vendor"], name="invmon_asset_vendor_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["project"], name="invmon_asset_project_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["warranty_start"], name="invmon_asset_warr_start_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["warranty_end"], name="invmon_asset_warr_end_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["assigned_object_type", "assigned_object_id"],
                name="invmon_asset_assigned_obj_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="probe",
            index=models.Index(fields=["serial"], name="invmon_probe_serial_idx"),
        ),
        migrations.AddIndex(
            model_name="probe",
            index=models.Index(fields=["time"], name="invmon_probe_time_idx"),
        ),
        migrations.AddIndex(
            model_name="probe",
            index=models.Index(fields=["serial", "time"], name="invmon_probe_serial_time_idx"),
        ),
    ]
