# Generated by Django 5.1.5 on 2025-03-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dcim", "0200_populate_mac_addresses"),
        ("extras", "0122_charfield_null_choices"),
        ("inventory_monitor", "0029_asset_invmon_asset_serial_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": (
                    "name",
                    "serial",
                    "partnumber",
                    "asset_number",
                    "project",
                    "inventory_item",
                    "vendor",
                    "quantity",
                    "price",
                    "order_contract",
                    "warranty_start",
                    "warranty_end",
                )
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["name"], name="invmon_asset_name_idx"),
        ),
    ]
