# Generated by Django 5.1.5 on 2025-03-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0200_populate_mac_addresses"),
        ("inventory_monitor", "0031_abra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="dcim.inventoryitem",
            ),
        ),
    ]
