# Generated by Django 5.1.5 on 2025-03-07 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0032_alter_asset_inventory_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": (
                    "name",
                    "serial",
                    "partnumber",
                    "asset_number",
                    "project",
                    "vendor",
                    "quantity",
                    "price",
                    "order_contract",
                    "warranty_start",
                    "warranty_end",
                )
            },
        ),
        migrations.RemoveField(
            model_name="asset",
            name="inventory_item",
        ),
    ]
