# Generated by Django 5.1.5 on 2025-03-07 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0033_alter_asset_options_remove_asset_inventory_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": (
                    "partnumber",
                    "serial",
                    "name",
                    "asset_number",
                    "project",
                    "vendor",
                    "quantity",
                    "price",
                    "order_contract",
                    "warranty_start",
                    "warranty_end",
                )
            },
        ),
    ]
