# Generated by Django 5.1.5 on 2025-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0122_charfield_null_choices"),
        ("inventory_monitor", "0034_alter_asset_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": (
                    "partnumber",
                    "serial",
                    "description",
                    "asset_number",
                    "project",
                    "vendor",
                    "quantity",
                    "price",
                    "order_contract",
                    "warranty_start",
                    "warranty_end",
                )
            },
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="invmon_asset_name_idx",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="name",
            new_name="description",
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["description"], name="invmon_asset_desc_idx"),
        ),
    ]
