# Generated by Django 5.1.5 on 2025-05-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_monitor", "0035_alter_asset_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abra",
            name="abra_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
