# Generated by Django 5.1.5 on 2025-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0123_journalentry_kind_default"),
        ("inventory_monitor", "0036_abra_abra_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="abra",
            index=models.Index(fields=["abra_id"], name="abra_id_idx"),
        ),
    ]
