# Generated by Django 5.1.5 on 2025-05-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_monitor", "0037_abra_abra_id_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="componentservice",
            options={
                "ordering": (
                    "service_start",
                    "service_end",
                    "service_price",
                    "service_category",
                    "service_category_vendor",
                    "asset",
                    "contract",
                )
            },
        ),
        migrations.RemoveField(
            model_name="componentservice",
            name="service_param",
        ),
    ]
