# Generated by Django 5.2.1 on 2025-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0128_tableconfig"),
        ("inventory_monitor", "0038_alter_componentservice_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ComponentService",
            new_name="AssetService",
        ),
        migrations.AlterField(
            model_name="abra",
            name="abra_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
