# Generated by Django 5.2.1 on 2025-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0128_tableconfig"),
        ("inventory_monitor", "0039_rename_componentservice_assetservice_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abra",
            old_name="activity_code",
            new_name="department_code",
        ),
        migrations.AddField(
            model_name="abra",
            name="project_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="abra",
            index=models.Index(fields=["department_code"], name="abra_deptcode_idx"),
        ),
        migrations.AddIndex(
            model_name="abra",
            index=models.Index(fields=["project_code"], name="abra_projcode_idx"),
        ),
    ]
