# Generated by Django 5.2.1 on 2025-06-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_monitor",
            "0040_rename_activity_code_abra_department_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": (
                    "partnumber",
                    "serial",
                    "description",
                    "project",
                    "vendor",
                    "quantity",
                    "price",
                    "order_contract",
                    "warranty_start",
                    "warranty_end",
                )
            },
        ),
        migrations.RemoveIndex(
            model_name="asset",
            name="invmon_asset_assetnum_idx",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="asset_number",
        ),
    ]
