# Generated by Django 5.2.5 on 2025-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0132_configcontextprofile'),
        ('inventory_monitor', '0043_rename_fields_and_relations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='externalinventory',
            name='abra_id_idx',
        ),
        migrations.RenameIndex(
            model_name='externalinventory',
            new_name='ext_inv_invnum_idx',
            old_name='abra_invnum_idx',
        ),
        migrations.RenameIndex(
            model_name='externalinventory',
            new_name='ext_inv_serial_idx',
            old_name='abra_serial_idx',
        ),
        migrations.RenameIndex(
            model_name='externalinventory',
            new_name='ext_inv_personid_idx',
            old_name='abra_personid_idx',
        ),
        migrations.RenameIndex(
            model_name='externalinventory',
            new_name='ext_inv_loccode_idx',
            old_name='abra_loccode_idx',
        ),
        migrations.RenameIndex(
            model_name='externalinventory',
            new_name='ext_inv_deptcode_idx',
            old_name='abra_deptcode_idx',
        ),
        migrations.RenameIndex(
            model_name='externalinventory',
            new_name='ext_inv_projcode_idx',
            old_name='abra_projcode_idx',
        ),
        migrations.RenameIndex(
            model_name='externalinventory',
            new_name='ext_inv_status_idx',
            old_name='abra_status_idx',
        ),
        migrations.AddIndex(
            model_name='externalinventory',
            index=models.Index(fields=['external_id'], name='ext_inv_id_idx'),
        ),
    ]
